2018/04/04 20:56:40 [crit] 246#246: *1 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:56:41 [crit] 246#246: *1 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:56:42 [crit] 246#246: *1 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:56:49 [crit] 246#246: *1 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.ph HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:56:51 [crit] 246#246: *1 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:02 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:02 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:03 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:03 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:03 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:03 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:04 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:04 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:04 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:04 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:04 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:05 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:13 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 21:00:53 [crit] 246#246: *30 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 21:00:54 [crit] 246#246: *30 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 21:00:55 [crit] 246#246: *30 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 21:02:18 [crit] 246#246: *35 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 21:02:18 [crit] 246#246: *35 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 21:02:19 [crit] 246#246: *35 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 21:02:19 [crit] 246#246: *35 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 21:02:19 [crit] 246#246: *35 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 21:02:22 [crit] 246#246: *35 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 21:04:15 [error] 822#822: *6 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function toArray() on null in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/views/layouts/main.php:33
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(336): require()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/mnt/e/PHP Stor...', Array)
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/mnt/e/PHP Stor...', Array, Object(frontend\controllers\SiteController))
#3 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit...')
#4 /mnt/e/PHP Storm Projects/" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /user/create HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/04 21:04:15 [error] 822#822: *6 FastCGI sent in stderr: "GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#5 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\w" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /user/create HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/04 21:04:44 [error] 822#822: *6 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function toArray() on null in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/views/layouts/main.php:33
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(336): require()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/mnt/e/PHP Stor...', Array)
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/mnt/e/PHP Stor...', Array, Object(frontend\controllers\SiteController))
#3 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit...')
#4 /mnt/e/PHP Storm Projects/" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /user/create HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/04 21:04:44 [error] 822#822: *6 FastCGI sent in stderr: "GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#5 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\w" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /user/create HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/04 21:04:52 [error] 822#822: *6 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function toArray() on null in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/views/layouts/main.php:33
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(336): require()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/mnt/e/PHP Stor...', Array)
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/mnt/e/PHP Stor...', Array, Object(frontend\controllers\SiteController))
#3 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit...')
#4 /mnt/e/PHP Storm Projects/" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /user/create HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/04 21:04:52 [error] 822#822: *6 FastCGI sent in stderr: "GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#5 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\w" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /user/create HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/04 21:24:33 [error] 1040#1040: *10 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: advanced.test, request: "GET /debug/default/toolbar?tag=5ac5266b87e1e HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test", referrer: "http://advanced.test/hello"
2018/04/04 22:10:43 [error] 3644#3644: *90 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: advanced.test, request: "GET /chat HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/04 22:20:07 [error] 3644#3644: *236 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function toArray() on null in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/views/layouts/main.php:33
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(336): require()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/mnt/e/PHP Stor...', Array)
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/mnt/e/PHP Stor...', Array, Object(frontend\controllers\SiteController))
#3 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit...')
#4 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#5 /mnt/e/PHP" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /signup HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/04 22:20:07 [error] 3644#3644: *236 FastCGI sent in stderr: " Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\w" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /signup HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/07 11:53:28 [error] 2944#2944: *296 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function toArray() on null in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/views/layouts/main.php:32
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(336): require()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/mnt/e/PHP Stor...', Array)
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/mnt/e/PHP Stor...', Array, Object(frontend\controllers\SiteController))
#3 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit...')
#4 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Arra" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /pjax-demo/index HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/07 11:53:28 [error] 2944#2944: *296 FastCGI sent in stderr: "y)
#5 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\w" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /pjax-demo/index HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/07 12:08:36 [error] 2941#2941: *465 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare frontend\controllers\ProjectController::actionCreateModal() in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/ProjectController.php on line 97" while reading response header from upstream, client: 127.0.0.1, server: advanced.test, request: "GET /project/create-modal HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/07 12:08:53 [error] 2941#2941: *465 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare frontend\controllers\ProjectController::actionCreateModal() in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/ProjectController.php on line 97" while reading response header from upstream, client: 127.0.0.1, server: advanced.test, request: "GET /project/create HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/07 12:08:56 [error] 2941#2941: *465 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare frontend\controllers\ProjectController::actionCreateModal() in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/ProjectController.php on line 97" while reading response header from upstream, client: 127.0.0.1, server: advanced.test, request: "GET /project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/07 12:09:00 [error] 2941#2941: *465 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare frontend\controllers\ProjectController::actionCreateModal() in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/ProjectController.php on line 97" while reading response header from upstream, client: 127.0.0.1, server: advanced.test, request: "GET /project/create HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test", referrer: "http://advanced.test/"
2018/04/07 12:13:44 [error] 2941#2941: *493 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/SiteController.php on line 81. in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/SiteController.php on li" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /site/?id=test HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/07 12:13:48 [error] 2941#2941: *493 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/SiteController.php on line 81. in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/SiteController.php on li" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /site/?id=test HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/07 12:13:52 [error] 2941#2941: *493 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/SiteController.php on line 81. in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/SiteController.php on li" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /site/?id=test HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/07 12:14:07 [error] 2941#2941: *493 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/SiteController.php on line 81. in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/SiteController.php on li" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /site/?id=test HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/07 12:48:06 [error] 2944#2944: *810 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: advanced.test, request: "GET /debug/default/toolbar?tag=5ac8a1e19589c HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test", referrer: "http://advanced.test/project/index"
2018/04/08 17:32:33 [error] 56#56: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/08 17:33:46 [error] 56#56: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/08 17:33:56 [error] 56#56: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/08 17:34:17 [error] 748#748: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/08 17:34:18 [error] 748#748: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/08 17:34:23 [error] 748#748: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/08 17:34:40 [error] 748#748: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/08 17:34:49 [error] 828#828: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/08 17:35:13 [error] 828#828: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/08 17:37:22 [error] 930#930: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
